name: Build & Upload APKs to anonfiles.com

on:
  workflow_dispatch:
    inputs:
      uploadProvider:
        description: 'mega.nz, anonfiles.com'
        required: true
        default: 'anonfiles.com'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
            # Or JDK 1.7 | JDK 1.9 | JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        # Or 1.7 | 1.9 | 11
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Checking Files
      run: find -name *.apk
    - name: Setup requires tool for uploading
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64
