name: Shell Sandbox

on:
  workflow_dispatch:
    inputs:
      uploadProvider:
        description: 'mega.nz, anonfiles.com'
        required: true
        default: 'anonfiles.com'


jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing
        run: |
          if [[ "${{ github.event.inputs.uploadProvider }}" = "anonfiles.com" ]]
          then
          echo -e '\033[0;32myes'
          else
          echo -e '\033[0;31mno'
          fi
